package com.stash.model;

public class AllStockModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.allstock.code
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.allstock.name
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.allstock.py
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private String py;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.allstock.industry
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private String industry;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.allstock.pe
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Double pe;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.allstock.pb
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Double pb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.allstock.totalvalue
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Double totalvalue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.allstock.currency
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Double currency;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.allstock.code
	 * @return  the value of public.allstock.code
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.allstock.code
	 * @param code  the value for public.allstock.code
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.allstock.name
	 * @return  the value of public.allstock.name
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.allstock.name
	 * @param name  the value for public.allstock.name
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.allstock.py
	 * @return  the value of public.allstock.py
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public String getPy() {
		return py;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.allstock.py
	 * @param py  the value for public.allstock.py
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setPy(String py) {
		this.py = py;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.allstock.industry
	 * @return  the value of public.allstock.industry
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public String getIndustry() {
		return industry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.allstock.industry
	 * @param industry  the value for public.allstock.industry
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setIndustry(String industry) {
		this.industry = industry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.allstock.pe
	 * @return  the value of public.allstock.pe
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Double getPe() {
		return pe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.allstock.pe
	 * @param pe  the value for public.allstock.pe
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setPe(Double pe) {
		this.pe = pe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.allstock.pb
	 * @return  the value of public.allstock.pb
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Double getPb() {
		return pb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.allstock.pb
	 * @param pb  the value for public.allstock.pb
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setPb(Double pb) {
		this.pb = pb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.allstock.totalvalue
	 * @return  the value of public.allstock.totalvalue
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Double getTotalvalue() {
		return totalvalue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.allstock.totalvalue
	 * @param totalvalue  the value for public.allstock.totalvalue
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setTotalvalue(Double totalvalue) {
		this.totalvalue = totalvalue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.allstock.currency
	 * @return  the value of public.allstock.currency
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Double getCurrency() {
		return currency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.allstock.currency
	 * @param currency  the value for public.allstock.currency
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setCurrency(Double currency) {
		this.currency = currency;
	}
}