package com.stash.model;

import java.util.Date;

public class BkrecordModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.bkrecord.id
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.bkrecord.code
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.bkrecord.name
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.bkrecord.increase
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Double increase;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.bkrecord.date
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Date date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.bkrecord.time
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Integer time;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.bkrecord.id
	 * @return  the value of public.bkrecord.id
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.bkrecord.id
	 * @param id  the value for public.bkrecord.id
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.bkrecord.code
	 * @return  the value of public.bkrecord.code
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.bkrecord.code
	 * @param code  the value for public.bkrecord.code
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.bkrecord.name
	 * @return  the value of public.bkrecord.name
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.bkrecord.name
	 * @param name  the value for public.bkrecord.name
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.bkrecord.increase
	 * @return  the value of public.bkrecord.increase
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Double getIncrease() {
		return increase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.bkrecord.increase
	 * @param increase  the value for public.bkrecord.increase
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setIncrease(Double increase) {
		this.increase = increase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.bkrecord.date
	 * @return  the value of public.bkrecord.date
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.bkrecord.date
	 * @param date  the value for public.bkrecord.date
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.bkrecord.time
	 * @return  the value of public.bkrecord.time
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Integer getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.bkrecord.time
	 * @param time  the value for public.bkrecord.time
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setTime(Integer time) {
		this.time = time;
	}
}