package com.stash.model;

import java.util.Date;

public class BkTransModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.candidate.id
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.candidate.preflist
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String preflist;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.candidate.time
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Date time;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.candidate.id
	 * @return  the value of public.candidate.id
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.candidate.id
	 * @param id  the value for public.candidate.id
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.candidate.preflist
	 * @return  the value of public.candidate.preflist
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getPreflist() {
		return preflist;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.candidate.preflist
	 * @param preflist  the value for public.candidate.preflist
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setPreflist(String preflist) {
		this.preflist = preflist;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.candidate.time
	 * @return  the value of public.candidate.time
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.candidate.time
	 * @param time  the value for public.candidate.time
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setTime(Date time) {
		this.time = time;
	}
}