package com.stash.model;

import java.util.Date;

public class CandRateModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.cand_rate.id
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.cand_rate.code
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.cand_rate.name
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.cand_rate.current
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Double current;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.cand_rate.a
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Double a;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.cand_rate.b
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Double b;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.cand_rate.r
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Double r;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.cand_rate.increase
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Double increase;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.cand_rate.time
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Date time;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.cand_rate.id
	 * @return  the value of public.cand_rate.id
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.cand_rate.id
	 * @param id  the value for public.cand_rate.id
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.cand_rate.code
	 * @return  the value of public.cand_rate.code
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.cand_rate.code
	 * @param code  the value for public.cand_rate.code
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.cand_rate.name
	 * @return  the value of public.cand_rate.name
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.cand_rate.name
	 * @param name  the value for public.cand_rate.name
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.cand_rate.current
	 * @return  the value of public.cand_rate.current
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Double getCurrent() {
		return current;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.cand_rate.current
	 * @param current  the value for public.cand_rate.current
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setCurrent(Double current) {
		this.current = current;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.cand_rate.a
	 * @return  the value of public.cand_rate.a
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Double getA() {
		return a;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.cand_rate.a
	 * @param a  the value for public.cand_rate.a
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setA(Double a) {
		this.a = a;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.cand_rate.b
	 * @return  the value of public.cand_rate.b
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Double getB() {
		return b;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.cand_rate.b
	 * @param b  the value for public.cand_rate.b
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setB(Double b) {
		this.b = b;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.cand_rate.r
	 * @return  the value of public.cand_rate.r
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Double getR() {
		return r;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.cand_rate.r
	 * @param r  the value for public.cand_rate.r
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setR(Double r) {
		this.r = r;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.cand_rate.increase
	 * @return  the value of public.cand_rate.increase
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Double getIncrease() {
		return increase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.cand_rate.increase
	 * @param increase  the value for public.cand_rate.increase
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setIncrease(Double increase) {
		this.increase = increase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.cand_rate.time
	 * @return  the value of public.cand_rate.time
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.cand_rate.time
	 * @param time  the value for public.cand_rate.time
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setTime(Date time) {
		this.time = time;
	}
}