package com.stash.model;

public class CategoryModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.category.code
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.category.name
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.category.type
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.category.content
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.category.code
	 * @return  the value of public.category.code
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.category.code
	 * @param code  the value for public.category.code
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.category.name
	 * @return  the value of public.category.name
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.category.name
	 * @param name  the value for public.category.name
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.category.type
	 * @return  the value of public.category.type
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.category.type
	 * @param type  the value for public.category.type
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.category.content
	 * @return  the value of public.category.content
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.category.content
	 * @param content  the value for public.category.content
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}
}