package com.stash.model;

import java.util.Date;

public class CollectModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.collect.code
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.collect.name
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.collect.date
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.collect.flag
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.collect.code
     *
     * @return the value of public.collect.code
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.collect.code
     *
     * @param code the value for public.collect.code
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.collect.name
     *
     * @return the value of public.collect.name
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.collect.name
     *
     * @param name the value for public.collect.name
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.collect.date
     *
     * @return the value of public.collect.date
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.collect.date
     *
     * @param date the value for public.collect.date
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.collect.flag
     *
     * @return the value of public.collect.flag
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.collect.flag
     *
     * @param flag the value for public.collect.flag
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}