package com.stash.model;

import java.util.Date;

public class CrecordModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.crecord.id
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.crecord.code
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.crecord.name
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.crecord.increase
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Double increase;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.crecord.date
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Date date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.crecord.time
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Integer time;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.crecord.id
	 * @return  the value of public.crecord.id
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.crecord.id
	 * @param id  the value for public.crecord.id
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.crecord.code
	 * @return  the value of public.crecord.code
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.crecord.code
	 * @param code  the value for public.crecord.code
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.crecord.name
	 * @return  the value of public.crecord.name
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.crecord.name
	 * @param name  the value for public.crecord.name
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.crecord.increase
	 * @return  the value of public.crecord.increase
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Double getIncrease() {
		return increase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.crecord.increase
	 * @param increase  the value for public.crecord.increase
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setIncrease(Double increase) {
		this.increase = increase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.crecord.date
	 * @return  the value of public.crecord.date
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.crecord.date
	 * @param date  the value for public.crecord.date
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.crecord.time
	 * @return  the value of public.crecord.time
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Integer getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.crecord.time
	 * @param time  the value for public.crecord.time
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setTime(Integer time) {
		this.time = time;
	}
}