package com.stash.model;

import java.util.Date;

public class CTransModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.c_trans.id
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.c_trans.code
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.c_trans.name
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.c_trans.increase
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Double increase;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.c_trans.trans
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Double trans;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.c_trans.time
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Date time;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.c_trans.id
	 * @return  the value of public.c_trans.id
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.c_trans.id
	 * @param id  the value for public.c_trans.id
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.c_trans.code
	 * @return  the value of public.c_trans.code
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.c_trans.code
	 * @param code  the value for public.c_trans.code
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.c_trans.name
	 * @return  the value of public.c_trans.name
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.c_trans.name
	 * @param name  the value for public.c_trans.name
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.c_trans.increase
	 * @return  the value of public.c_trans.increase
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Double getIncrease() {
		return increase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.c_trans.increase
	 * @param increase  the value for public.c_trans.increase
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setIncrease(Double increase) {
		this.increase = increase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.c_trans.trans
	 * @return  the value of public.c_trans.trans
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Double getTrans() {
		return trans;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.c_trans.trans
	 * @param trans  the value for public.c_trans.trans
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setTrans(Double trans) {
		this.trans = trans;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.c_trans.time
	 * @return  the value of public.c_trans.time
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.c_trans.time
	 * @param time  the value for public.c_trans.time
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setTime(Date time) {
		this.time = time;
	}
}