package com.stash.model;

import java.util.Date;

public class DailyRateModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.daily_rate.id
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.daily_rate.code
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.daily_rate.a
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Double a;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.daily_rate.b
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Double b;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.daily_rate.r
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Double r;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.daily_rate.date
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Date date;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.daily_rate.id
	 * @return  the value of public.daily_rate.id
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.daily_rate.id
	 * @param id  the value for public.daily_rate.id
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.daily_rate.code
	 * @return  the value of public.daily_rate.code
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.daily_rate.code
	 * @param code  the value for public.daily_rate.code
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.daily_rate.a
	 * @return  the value of public.daily_rate.a
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Double getA() {
		return a;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.daily_rate.a
	 * @param a  the value for public.daily_rate.a
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setA(Double a) {
		this.a = a;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.daily_rate.b
	 * @return  the value of public.daily_rate.b
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Double getB() {
		return b;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.daily_rate.b
	 * @param b  the value for public.daily_rate.b
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setB(Double b) {
		this.b = b;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.daily_rate.r
	 * @return  the value of public.daily_rate.r
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Double getR() {
		return r;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.daily_rate.r
	 * @param r  the value for public.daily_rate.r
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setR(Double r) {
		this.r = r;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.daily_rate.date
	 * @return  the value of public.daily_rate.date
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.daily_rate.date
	 * @param date  the value for public.daily_rate.date
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setDate(Date date) {
		this.date = date;
	}
}