package com.stash.model;

import java.util.Date;

public class DirectorModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.director.id
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.director.code
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.director.name
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.director.time
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.director.price
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Double price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.director.type
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Short type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.director.level
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Integer level;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.director.flag
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Short flag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.director.total
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Integer total;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.director.arrow
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private String arrow;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.director.id
	 * @return  the value of public.director.id
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.director.id
	 * @param id  the value for public.director.id
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.director.code
	 * @return  the value of public.director.code
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.director.code
	 * @param code  the value for public.director.code
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.director.name
	 * @return  the value of public.director.name
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.director.name
	 * @param name  the value for public.director.name
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.director.time
	 * @return  the value of public.director.time
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.director.time
	 * @param time  the value for public.director.time
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.director.price
	 * @return  the value of public.director.price
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.director.price
	 * @param price  the value for public.director.price
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.director.type
	 * @return  the value of public.director.type
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Short getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.director.type
	 * @param type  the value for public.director.type
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setType(Short type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.director.level
	 * @return  the value of public.director.level
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Integer getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.director.level
	 * @param level  the value for public.director.level
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setLevel(Integer level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.director.flag
	 * @return  the value of public.director.flag
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Short getFlag() {
		return flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.director.flag
	 * @param flag  the value for public.director.flag
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setFlag(Short flag) {
		this.flag = flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.director.total
	 * @return  the value of public.director.total
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Integer getTotal() {
		return total;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.director.total
	 * @param total  the value for public.director.total
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setTotal(Integer total) {
		this.total = total;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.director.arrow
	 * @return  the value of public.director.arrow
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public String getArrow() {
		return arrow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.director.arrow
	 * @param arrow  the value for public.director.arrow
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setArrow(String arrow) {
		this.arrow = arrow;
	}
}