package com.stash.model;

public class HistoryModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.history.id
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.history.ftime
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Integer ftime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.history.ltime
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Integer ltime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.history.record
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String record;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.history.type
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String type;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.history.id
	 * @return  the value of public.history.id
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.history.id
	 * @param id  the value for public.history.id
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.history.ftime
	 * @return  the value of public.history.ftime
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Integer getFtime() {
		return ftime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.history.ftime
	 * @param ftime  the value for public.history.ftime
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setFtime(Integer ftime) {
		this.ftime = ftime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.history.ltime
	 * @return  the value of public.history.ltime
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Integer getLtime() {
		return ltime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.history.ltime
	 * @param ltime  the value for public.history.ltime
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setLtime(Integer ltime) {
		this.ltime = ltime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.history.record
	 * @return  the value of public.history.record
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getRecord() {
		return record;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.history.record
	 * @param record  the value for public.history.record
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setRecord(String record) {
		this.record = record;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.history.type
	 * @return  the value of public.history.type
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.history.type
	 * @param type  the value for public.history.type
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setType(String type) {
		this.type = type;
	}
}