package com.stash.model;

import java.util.Date;

public class HolderModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.holder.code
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.holder.name
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.holder.time
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.holder.trans
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Double trans;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.holder.signal
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Integer signal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.holder.ascrate
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Double ascrate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.holder.descrate
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Double descrate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.holder.equalrate
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Double equalrate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.holder.code
	 * @return  the value of public.holder.code
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.holder.code
	 * @param code  the value for public.holder.code
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.holder.name
	 * @return  the value of public.holder.name
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.holder.name
	 * @param name  the value for public.holder.name
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.holder.time
	 * @return  the value of public.holder.time
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.holder.time
	 * @param time  the value for public.holder.time
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.holder.trans
	 * @return  the value of public.holder.trans
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Double getTrans() {
		return trans;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.holder.trans
	 * @param trans  the value for public.holder.trans
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setTrans(Double trans) {
		this.trans = trans;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.holder.signal
	 * @return  the value of public.holder.signal
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Integer getSignal() {
		return signal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.holder.signal
	 * @param signal  the value for public.holder.signal
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setSignal(Integer signal) {
		this.signal = signal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.holder.ascrate
	 * @return  the value of public.holder.ascrate
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Double getAscrate() {
		return ascrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.holder.ascrate
	 * @param ascrate  the value for public.holder.ascrate
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setAscrate(Double ascrate) {
		this.ascrate = ascrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.holder.descrate
	 * @return  the value of public.holder.descrate
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Double getDescrate() {
		return descrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.holder.descrate
	 * @param descrate  the value for public.holder.descrate
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setDescrate(Double descrate) {
		this.descrate = descrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.holder.equalrate
	 * @return  the value of public.holder.equalrate
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Double getEqualrate() {
		return equalrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.holder.equalrate
	 * @param equalrate  the value for public.holder.equalrate
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setEqualrate(Double equalrate) {
		this.equalrate = equalrate;
	}
}