package com.stash.model;

import java.util.Date;

public class IndexrecordModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.indexrecord.id
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.indexrecord.code
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.indexrecord.name
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.indexrecord.close
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Double close;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.indexrecord.open
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Double open;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.indexrecord.current
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Double current;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.indexrecord.high
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Double high;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.indexrecord.low
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Double low;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.indexrecord.clmn
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Double clmn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.indexrecord.money
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Double money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.indexrecord.avg
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Double avg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.indexrecord.date
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Date date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.indexrecord.time
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Integer time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.indexrecord.flag
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String flag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.indexrecord.id
	 * @return  the value of public.indexrecord.id
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.indexrecord.id
	 * @param id  the value for public.indexrecord.id
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.indexrecord.code
	 * @return  the value of public.indexrecord.code
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.indexrecord.code
	 * @param code  the value for public.indexrecord.code
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.indexrecord.name
	 * @return  the value of public.indexrecord.name
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.indexrecord.name
	 * @param name  the value for public.indexrecord.name
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.indexrecord.close
	 * @return  the value of public.indexrecord.close
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Double getClose() {
		return close;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.indexrecord.close
	 * @param close  the value for public.indexrecord.close
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setClose(Double close) {
		this.close = close;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.indexrecord.open
	 * @return  the value of public.indexrecord.open
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Double getOpen() {
		return open;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.indexrecord.open
	 * @param open  the value for public.indexrecord.open
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setOpen(Double open) {
		this.open = open;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.indexrecord.current
	 * @return  the value of public.indexrecord.current
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Double getCurrent() {
		return current;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.indexrecord.current
	 * @param current  the value for public.indexrecord.current
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setCurrent(Double current) {
		this.current = current;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.indexrecord.high
	 * @return  the value of public.indexrecord.high
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Double getHigh() {
		return high;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.indexrecord.high
	 * @param high  the value for public.indexrecord.high
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setHigh(Double high) {
		this.high = high;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.indexrecord.low
	 * @return  the value of public.indexrecord.low
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Double getLow() {
		return low;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.indexrecord.low
	 * @param low  the value for public.indexrecord.low
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setLow(Double low) {
		this.low = low;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.indexrecord.clmn
	 * @return  the value of public.indexrecord.clmn
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Double getClmn() {
		return clmn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.indexrecord.clmn
	 * @param clmn  the value for public.indexrecord.clmn
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setClmn(Double clmn) {
		this.clmn = clmn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.indexrecord.money
	 * @return  the value of public.indexrecord.money
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Double getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.indexrecord.money
	 * @param money  the value for public.indexrecord.money
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setMoney(Double money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.indexrecord.avg
	 * @return  the value of public.indexrecord.avg
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Double getAvg() {
		return avg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.indexrecord.avg
	 * @param avg  the value for public.indexrecord.avg
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setAvg(Double avg) {
		this.avg = avg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.indexrecord.date
	 * @return  the value of public.indexrecord.date
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.indexrecord.date
	 * @param date  the value for public.indexrecord.date
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.indexrecord.time
	 * @return  the value of public.indexrecord.time
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Integer getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.indexrecord.time
	 * @param time  the value for public.indexrecord.time
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setTime(Integer time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.indexrecord.flag
	 * @return  the value of public.indexrecord.flag
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getFlag() {
		return flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.indexrecord.flag
	 * @param flag  the value for public.indexrecord.flag
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setFlag(String flag) {
		this.flag = flag;
	}
}