package com.stash.model;

import java.util.Date;

public class InspectModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.inspect.id
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.inspect.code
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.inspect.name
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.inspect.type
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.inspect.opt
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String opt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.inspect.value
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Double value;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.inspect.create_date
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.inspect.flag
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Integer flag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.inspect.id
	 * @return  the value of public.inspect.id
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.inspect.id
	 * @param id  the value for public.inspect.id
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.inspect.code
	 * @return  the value of public.inspect.code
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.inspect.code
	 * @param code  the value for public.inspect.code
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.inspect.name
	 * @return  the value of public.inspect.name
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.inspect.name
	 * @param name  the value for public.inspect.name
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.inspect.type
	 * @return  the value of public.inspect.type
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.inspect.type
	 * @param type  the value for public.inspect.type
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.inspect.opt
	 * @return  the value of public.inspect.opt
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getOpt() {
		return opt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.inspect.opt
	 * @param opt  the value for public.inspect.opt
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setOpt(String opt) {
		this.opt = opt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.inspect.value
	 * @return  the value of public.inspect.value
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Double getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.inspect.value
	 * @param value  the value for public.inspect.value
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setValue(Double value) {
		this.value = value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.inspect.create_date
	 * @return  the value of public.inspect.create_date
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.inspect.create_date
	 * @param createDate  the value for public.inspect.create_date
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.inspect.flag
	 * @return  the value of public.inspect.flag
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Integer getFlag() {
		return flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.inspect.flag
	 * @param flag  the value for public.inspect.flag
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setFlag(Integer flag) {
		this.flag = flag;
	}
}