package com.stash.model;

import java.util.Date;

public class MessageModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.message.id
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.message.code
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.message.name
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.message.message
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.message.flag
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private Integer flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.message.time
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.message.updatetime
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.message.id
     *
     * @return the value of public.message.id
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.message.id
     *
     * @param id the value for public.message.id
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.message.code
     *
     * @return the value of public.message.code
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.message.code
     *
     * @param code the value for public.message.code
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.message.name
     *
     * @return the value of public.message.name
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.message.name
     *
     * @param name the value for public.message.name
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.message.message
     *
     * @return the value of public.message.message
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.message.message
     *
     * @param message the value for public.message.message
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.message.flag
     *
     * @return the value of public.message.flag
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.message.flag
     *
     * @param flag the value for public.message.flag
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.message.time
     *
     * @return the value of public.message.time
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.message.time
     *
     * @param time the value for public.message.time
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.message.updatetime
     *
     * @return the value of public.message.updatetime
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.message.updatetime
     *
     * @param updatetime the value for public.message.updatetime
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}