package com.stash.model;

import java.util.Date;

public class MincolumnModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.mincolumn.code
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.mincolumn.date
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.mincolumn.code
     *
     * @return the value of public.mincolumn.code
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.mincolumn.code
     *
     * @param code the value for public.mincolumn.code
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.mincolumn.date
     *
     * @return the value of public.mincolumn.date
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.mincolumn.date
     *
     * @param date the value for public.mincolumn.date
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setDate(Date date) {
        this.date = date;
    }
}