package com.stash.model;

import java.util.Date;

public class PayResultModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.pay_result.orderid
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.pay_result.appid
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String appId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.pay_result.userid
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.pay_result.paytype
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Integer payType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.pay_result.resultcode
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Integer resultCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.pay_result.resultstring
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String resultString;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.pay_result.tradeid
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String tradeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.pay_result.amount
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Double amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.pay_result.paytime
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Date payTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.pay_result.sign
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String sign;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.pay_result.comment
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String comment;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.pay_result.orderid
	 * @return  the value of public.pay_result.orderid
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.pay_result.orderid
	 * @param orderId  the value for public.pay_result.orderid
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.pay_result.appid
	 * @return  the value of public.pay_result.appid
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getAppId() {
		return appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.pay_result.appid
	 * @param appId  the value for public.pay_result.appid
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setAppId(String appId) {
		this.appId = appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.pay_result.userid
	 * @return  the value of public.pay_result.userid
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.pay_result.userid
	 * @param userId  the value for public.pay_result.userid
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.pay_result.paytype
	 * @return  the value of public.pay_result.paytype
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Integer getPayType() {
		return payType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.pay_result.paytype
	 * @param payType  the value for public.pay_result.paytype
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setPayType(Integer payType) {
		this.payType = payType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.pay_result.resultcode
	 * @return  the value of public.pay_result.resultcode
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Integer getResultCode() {
		return resultCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.pay_result.resultcode
	 * @param resultCode  the value for public.pay_result.resultcode
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setResultCode(Integer resultCode) {
		this.resultCode = resultCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.pay_result.resultstring
	 * @return  the value of public.pay_result.resultstring
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getResultString() {
		return resultString;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.pay_result.resultstring
	 * @param resultString  the value for public.pay_result.resultstring
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setResultString(String resultString) {
		this.resultString = resultString;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.pay_result.tradeid
	 * @return  the value of public.pay_result.tradeid
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getTradeId() {
		return tradeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.pay_result.tradeid
	 * @param tradeId  the value for public.pay_result.tradeid
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setTradeId(String tradeId) {
		this.tradeId = tradeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.pay_result.amount
	 * @return  the value of public.pay_result.amount
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Double getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.pay_result.amount
	 * @param amount  the value for public.pay_result.amount
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setAmount(Double amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.pay_result.paytime
	 * @return  the value of public.pay_result.paytime
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Date getPayTime() {
		return payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.pay_result.paytime
	 * @param payTime  the value for public.pay_result.paytime
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.pay_result.sign
	 * @return  the value of public.pay_result.sign
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getSign() {
		return sign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.pay_result.sign
	 * @param sign  the value for public.pay_result.sign
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setSign(String sign) {
		this.sign = sign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.pay_result.comment
	 * @return  the value of public.pay_result.comment
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.pay_result.comment
	 * @param comment  the value for public.pay_result.comment
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}
}