package com.stash.model;

public class SignModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.sign.code
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.sign.sell
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Integer sell;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.sign.buy
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Integer buy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.sign.prefbuy
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Double prefBuy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.sign.prefsell
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Double prefSell;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.sign.current
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Double current;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.sign.high
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Double high;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.sign.low
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Double low;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.sign.avg
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Double avg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.sign.concept
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String concept;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.sign.code
	 * @return  the value of public.sign.code
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.sign.code
	 * @param code  the value for public.sign.code
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.sign.sell
	 * @return  the value of public.sign.sell
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Integer getSell() {
		return sell;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.sign.sell
	 * @param sell  the value for public.sign.sell
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setSell(Integer sell) {
		this.sell = sell;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.sign.buy
	 * @return  the value of public.sign.buy
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Integer getBuy() {
		return buy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.sign.buy
	 * @param buy  the value for public.sign.buy
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setBuy(Integer buy) {
		this.buy = buy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.sign.prefbuy
	 * @return  the value of public.sign.prefbuy
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Double getPrefBuy() {
		return prefBuy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.sign.prefbuy
	 * @param prefBuy  the value for public.sign.prefbuy
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setPrefBuy(Double prefBuy) {
		this.prefBuy = prefBuy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.sign.prefsell
	 * @return  the value of public.sign.prefsell
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Double getPrefSell() {
		return prefSell;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.sign.prefsell
	 * @param prefSell  the value for public.sign.prefsell
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setPrefSell(Double prefSell) {
		this.prefSell = prefSell;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.sign.current
	 * @return  the value of public.sign.current
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Double getCurrent() {
		return current;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.sign.current
	 * @param current  the value for public.sign.current
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setCurrent(Double current) {
		this.current = current;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.sign.high
	 * @return  the value of public.sign.high
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Double getHigh() {
		return high;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.sign.high
	 * @param high  the value for public.sign.high
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setHigh(Double high) {
		this.high = high;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.sign.low
	 * @return  the value of public.sign.low
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Double getLow() {
		return low;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.sign.low
	 * @param low  the value for public.sign.low
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setLow(Double low) {
		this.low = low;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.sign.avg
	 * @return  the value of public.sign.avg
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Double getAvg() {
		return avg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.sign.avg
	 * @param avg  the value for public.sign.avg
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setAvg(Double avg) {
		this.avg = avg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.sign.concept
	 * @return  the value of public.sign.concept
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getConcept() {
		return concept;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.sign.concept
	 * @param concept  the value for public.sign.concept
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setConcept(String concept) {
		this.concept = concept;
	}
}