package com.stash.model;

import java.util.Date;

public class StockdailyModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stockdaily.id
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stockdaily.code
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stockdaily.name
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stockdaily.close
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private Double close;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stockdaily.open
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private Double open;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stockdaily.current
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private Double current;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stockdaily.high
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private Double high;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stockdaily.low
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private Double low;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stockdaily.clmn
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private Double clmn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stockdaily.money
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private Double money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stockdaily.avg
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private Double avg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stockdaily.date
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stockdaily.time
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private Integer time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stockdaily.flag
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private String flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stockdaily.id
     *
     * @return the value of public.stockdaily.id
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stockdaily.id
     *
     * @param id the value for public.stockdaily.id
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stockdaily.code
     *
     * @return the value of public.stockdaily.code
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stockdaily.code
     *
     * @param code the value for public.stockdaily.code
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stockdaily.name
     *
     * @return the value of public.stockdaily.name
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stockdaily.name
     *
     * @param name the value for public.stockdaily.name
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stockdaily.close
     *
     * @return the value of public.stockdaily.close
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public Double getClose() {
        return close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stockdaily.close
     *
     * @param close the value for public.stockdaily.close
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setClose(Double close) {
        this.close = close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stockdaily.open
     *
     * @return the value of public.stockdaily.open
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public Double getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stockdaily.open
     *
     * @param open the value for public.stockdaily.open
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setOpen(Double open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stockdaily.current
     *
     * @return the value of public.stockdaily.current
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public Double getCurrent() {
        return current;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stockdaily.current
     *
     * @param current the value for public.stockdaily.current
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setCurrent(Double current) {
        this.current = current;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stockdaily.high
     *
     * @return the value of public.stockdaily.high
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public Double getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stockdaily.high
     *
     * @param high the value for public.stockdaily.high
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setHigh(Double high) {
        this.high = high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stockdaily.low
     *
     * @return the value of public.stockdaily.low
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public Double getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stockdaily.low
     *
     * @param low the value for public.stockdaily.low
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setLow(Double low) {
        this.low = low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stockdaily.clmn
     *
     * @return the value of public.stockdaily.clmn
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public Double getClmn() {
        return clmn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stockdaily.clmn
     *
     * @param clmn the value for public.stockdaily.clmn
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setClmn(Double clmn) {
        this.clmn = clmn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stockdaily.money
     *
     * @return the value of public.stockdaily.money
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stockdaily.money
     *
     * @param money the value for public.stockdaily.money
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stockdaily.avg
     *
     * @return the value of public.stockdaily.avg
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public Double getAvg() {
        return avg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stockdaily.avg
     *
     * @param avg the value for public.stockdaily.avg
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setAvg(Double avg) {
        this.avg = avg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stockdaily.date
     *
     * @return the value of public.stockdaily.date
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stockdaily.date
     *
     * @param date the value for public.stockdaily.date
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stockdaily.time
     *
     * @return the value of public.stockdaily.time
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stockdaily.time
     *
     * @param time the value for public.stockdaily.time
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stockdaily.flag
     *
     * @return the value of public.stockdaily.flag
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stockdaily.flag
     *
     * @param flag the value for public.stockdaily.flag
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }
}