package com.stash.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class StockactionModelExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.stockaction
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.stockaction
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.stockaction
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockaction
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public StockactionModelExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockaction
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockaction
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockaction
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockaction
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockaction
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockaction
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockaction
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockaction
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockaction
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockaction
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.stockaction
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andActionIsNull() {
			addCriterion("action is null");
			return (Criteria) this;
		}

		public Criteria andActionIsNotNull() {
			addCriterion("action is not null");
			return (Criteria) this;
		}

		public Criteria andActionEqualTo(Integer value) {
			addCriterion("action =", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionNotEqualTo(Integer value) {
			addCriterion("action <>", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionGreaterThan(Integer value) {
			addCriterion("action >", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionGreaterThanOrEqualTo(Integer value) {
			addCriterion("action >=", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionLessThan(Integer value) {
			addCriterion("action <", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionLessThanOrEqualTo(Integer value) {
			addCriterion("action <=", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionIn(List<Integer> values) {
			addCriterion("action in", values, "action");
			return (Criteria) this;
		}

		public Criteria andActionNotIn(List<Integer> values) {
			addCriterion("action not in", values, "action");
			return (Criteria) this;
		}

		public Criteria andActionBetween(Integer value1, Integer value2) {
			addCriterion("action between", value1, value2, "action");
			return (Criteria) this;
		}

		public Criteria andActionNotBetween(Integer value1, Integer value2) {
			addCriterion("action not between", value1, value2, "action");
			return (Criteria) this;
		}

		public Criteria andFtimeIsNull() {
			addCriterion("ftime is null");
			return (Criteria) this;
		}

		public Criteria andFtimeIsNotNull() {
			addCriterion("ftime is not null");
			return (Criteria) this;
		}

		public Criteria andFtimeEqualTo(Integer value) {
			addCriterion("ftime =", value, "ftime");
			return (Criteria) this;
		}

		public Criteria andFtimeNotEqualTo(Integer value) {
			addCriterion("ftime <>", value, "ftime");
			return (Criteria) this;
		}

		public Criteria andFtimeGreaterThan(Integer value) {
			addCriterion("ftime >", value, "ftime");
			return (Criteria) this;
		}

		public Criteria andFtimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("ftime >=", value, "ftime");
			return (Criteria) this;
		}

		public Criteria andFtimeLessThan(Integer value) {
			addCriterion("ftime <", value, "ftime");
			return (Criteria) this;
		}

		public Criteria andFtimeLessThanOrEqualTo(Integer value) {
			addCriterion("ftime <=", value, "ftime");
			return (Criteria) this;
		}

		public Criteria andFtimeIn(List<Integer> values) {
			addCriterion("ftime in", values, "ftime");
			return (Criteria) this;
		}

		public Criteria andFtimeNotIn(List<Integer> values) {
			addCriterion("ftime not in", values, "ftime");
			return (Criteria) this;
		}

		public Criteria andFtimeBetween(Integer value1, Integer value2) {
			addCriterion("ftime between", value1, value2, "ftime");
			return (Criteria) this;
		}

		public Criteria andFtimeNotBetween(Integer value1, Integer value2) {
			addCriterion("ftime not between", value1, value2, "ftime");
			return (Criteria) this;
		}

		public Criteria andLtimeIsNull() {
			addCriterion("ltime is null");
			return (Criteria) this;
		}

		public Criteria andLtimeIsNotNull() {
			addCriterion("ltime is not null");
			return (Criteria) this;
		}

		public Criteria andLtimeEqualTo(Integer value) {
			addCriterion("ltime =", value, "ltime");
			return (Criteria) this;
		}

		public Criteria andLtimeNotEqualTo(Integer value) {
			addCriterion("ltime <>", value, "ltime");
			return (Criteria) this;
		}

		public Criteria andLtimeGreaterThan(Integer value) {
			addCriterion("ltime >", value, "ltime");
			return (Criteria) this;
		}

		public Criteria andLtimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("ltime >=", value, "ltime");
			return (Criteria) this;
		}

		public Criteria andLtimeLessThan(Integer value) {
			addCriterion("ltime <", value, "ltime");
			return (Criteria) this;
		}

		public Criteria andLtimeLessThanOrEqualTo(Integer value) {
			addCriterion("ltime <=", value, "ltime");
			return (Criteria) this;
		}

		public Criteria andLtimeIn(List<Integer> values) {
			addCriterion("ltime in", values, "ltime");
			return (Criteria) this;
		}

		public Criteria andLtimeNotIn(List<Integer> values) {
			addCriterion("ltime not in", values, "ltime");
			return (Criteria) this;
		}

		public Criteria andLtimeBetween(Integer value1, Integer value2) {
			addCriterion("ltime between", value1, value2, "ltime");
			return (Criteria) this;
		}

		public Criteria andLtimeNotBetween(Integer value1, Integer value2) {
			addCriterion("ltime not between", value1, value2, "ltime");
			return (Criteria) this;
		}

		public Criteria andTimeIsNull() {
			addCriterion("time is null");
			return (Criteria) this;
		}

		public Criteria andTimeIsNotNull() {
			addCriterion("time is not null");
			return (Criteria) this;
		}

		public Criteria andTimeEqualTo(Date value) {
			addCriterionForJDBCDate("time =", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("time <>", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("time >", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("time >=", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLessThan(Date value) {
			addCriterionForJDBCDate("time <", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("time <=", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeIn(List<Date> values) {
			addCriterionForJDBCDate("time in", values, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("time not in", values, "time");
			return (Criteria) this;
		}

		public Criteria andTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("time between", value1, value2, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("time not between", value1, value2, "time");
			return (Criteria) this;
		}

		public Criteria andQueueIsNull() {
			addCriterion("queue is null");
			return (Criteria) this;
		}

		public Criteria andQueueIsNotNull() {
			addCriterion("queue is not null");
			return (Criteria) this;
		}

		public Criteria andQueueEqualTo(String value) {
			addCriterion("queue =", value, "queue");
			return (Criteria) this;
		}

		public Criteria andQueueNotEqualTo(String value) {
			addCriterion("queue <>", value, "queue");
			return (Criteria) this;
		}

		public Criteria andQueueGreaterThan(String value) {
			addCriterion("queue >", value, "queue");
			return (Criteria) this;
		}

		public Criteria andQueueGreaterThanOrEqualTo(String value) {
			addCriterion("queue >=", value, "queue");
			return (Criteria) this;
		}

		public Criteria andQueueLessThan(String value) {
			addCriterion("queue <", value, "queue");
			return (Criteria) this;
		}

		public Criteria andQueueLessThanOrEqualTo(String value) {
			addCriterion("queue <=", value, "queue");
			return (Criteria) this;
		}

		public Criteria andQueueLike(String value) {
			addCriterion("queue like", value, "queue");
			return (Criteria) this;
		}

		public Criteria andQueueNotLike(String value) {
			addCriterion("queue not like", value, "queue");
			return (Criteria) this;
		}

		public Criteria andQueueIn(List<String> values) {
			addCriterion("queue in", values, "queue");
			return (Criteria) this;
		}

		public Criteria andQueueNotIn(List<String> values) {
			addCriterion("queue not in", values, "queue");
			return (Criteria) this;
		}

		public Criteria andQueueBetween(String value1, String value2) {
			addCriterion("queue between", value1, value2, "queue");
			return (Criteria) this;
		}

		public Criteria andQueueNotBetween(String value1, String value2) {
			addCriterion("queue not between", value1, value2, "queue");
			return (Criteria) this;
		}

		public Criteria andGwIsNull() {
			addCriterion("gw is null");
			return (Criteria) this;
		}

		public Criteria andGwIsNotNull() {
			addCriterion("gw is not null");
			return (Criteria) this;
		}

		public Criteria andGwEqualTo(String value) {
			addCriterion("gw =", value, "gw");
			return (Criteria) this;
		}

		public Criteria andGwNotEqualTo(String value) {
			addCriterion("gw <>", value, "gw");
			return (Criteria) this;
		}

		public Criteria andGwGreaterThan(String value) {
			addCriterion("gw >", value, "gw");
			return (Criteria) this;
		}

		public Criteria andGwGreaterThanOrEqualTo(String value) {
			addCriterion("gw >=", value, "gw");
			return (Criteria) this;
		}

		public Criteria andGwLessThan(String value) {
			addCriterion("gw <", value, "gw");
			return (Criteria) this;
		}

		public Criteria andGwLessThanOrEqualTo(String value) {
			addCriterion("gw <=", value, "gw");
			return (Criteria) this;
		}

		public Criteria andGwLike(String value) {
			addCriterion("gw like", value, "gw");
			return (Criteria) this;
		}

		public Criteria andGwNotLike(String value) {
			addCriterion("gw not like", value, "gw");
			return (Criteria) this;
		}

		public Criteria andGwIn(List<String> values) {
			addCriterion("gw in", values, "gw");
			return (Criteria) this;
		}

		public Criteria andGwNotIn(List<String> values) {
			addCriterion("gw not in", values, "gw");
			return (Criteria) this;
		}

		public Criteria andGwBetween(String value1, String value2) {
			addCriterion("gw between", value1, value2, "gw");
			return (Criteria) this;
		}

		public Criteria andGwNotBetween(String value1, String value2) {
			addCriterion("gw not between", value1, value2, "gw");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(Integer value) {
			addCriterion("type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(Integer value) {
			addCriterion("type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(Integer value) {
			addCriterion("type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(Integer value) {
			addCriterion("type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(Integer value) {
			addCriterion("type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<Integer> values) {
			addCriterion("type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<Integer> values) {
			addCriterion("type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(Integer value1, Integer value2) {
			addCriterion("type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("type not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andContentIsNull() {
			addCriterion("content is null");
			return (Criteria) this;
		}

		public Criteria andContentIsNotNull() {
			addCriterion("content is not null");
			return (Criteria) this;
		}

		public Criteria andContentEqualTo(String value) {
			addCriterion("content =", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotEqualTo(String value) {
			addCriterion("content <>", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThan(String value) {
			addCriterion("content >", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThanOrEqualTo(String value) {
			addCriterion("content >=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThan(String value) {
			addCriterion("content <", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThanOrEqualTo(String value) {
			addCriterion("content <=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLike(String value) {
			addCriterion("content like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotLike(String value) {
			addCriterion("content not like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentIn(List<String> values) {
			addCriterion("content in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotIn(List<String> values) {
			addCriterion("content not in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentBetween(String value1, String value2) {
			addCriterion("content between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotBetween(String value1, String value2) {
			addCriterion("content not between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andDetailIsNull() {
			addCriterion("detail is null");
			return (Criteria) this;
		}

		public Criteria andDetailIsNotNull() {
			addCriterion("detail is not null");
			return (Criteria) this;
		}

		public Criteria andDetailEqualTo(String value) {
			addCriterion("detail =", value, "detail");
			return (Criteria) this;
		}

		public Criteria andDetailNotEqualTo(String value) {
			addCriterion("detail <>", value, "detail");
			return (Criteria) this;
		}

		public Criteria andDetailGreaterThan(String value) {
			addCriterion("detail >", value, "detail");
			return (Criteria) this;
		}

		public Criteria andDetailGreaterThanOrEqualTo(String value) {
			addCriterion("detail >=", value, "detail");
			return (Criteria) this;
		}

		public Criteria andDetailLessThan(String value) {
			addCriterion("detail <", value, "detail");
			return (Criteria) this;
		}

		public Criteria andDetailLessThanOrEqualTo(String value) {
			addCriterion("detail <=", value, "detail");
			return (Criteria) this;
		}

		public Criteria andDetailLike(String value) {
			addCriterion("detail like", value, "detail");
			return (Criteria) this;
		}

		public Criteria andDetailNotLike(String value) {
			addCriterion("detail not like", value, "detail");
			return (Criteria) this;
		}

		public Criteria andDetailIn(List<String> values) {
			addCriterion("detail in", values, "detail");
			return (Criteria) this;
		}

		public Criteria andDetailNotIn(List<String> values) {
			addCriterion("detail not in", values, "detail");
			return (Criteria) this;
		}

		public Criteria andDetailBetween(String value1, String value2) {
			addCriterion("detail between", value1, value2, "detail");
			return (Criteria) this;
		}

		public Criteria andDetailNotBetween(String value1, String value2) {
			addCriterion("detail not between", value1, value2, "detail");
			return (Criteria) this;
		}

		public Criteria andFlagIsNull() {
			addCriterion("flag is null");
			return (Criteria) this;
		}

		public Criteria andFlagIsNotNull() {
			addCriterion("flag is not null");
			return (Criteria) this;
		}

		public Criteria andFlagEqualTo(Integer value) {
			addCriterion("flag =", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagNotEqualTo(Integer value) {
			addCriterion("flag <>", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagGreaterThan(Integer value) {
			addCriterion("flag >", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagGreaterThanOrEqualTo(Integer value) {
			addCriterion("flag >=", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagLessThan(Integer value) {
			addCriterion("flag <", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagLessThanOrEqualTo(Integer value) {
			addCriterion("flag <=", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagIn(List<Integer> values) {
			addCriterion("flag in", values, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagNotIn(List<Integer> values) {
			addCriterion("flag not in", values, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagBetween(Integer value1, Integer value2) {
			addCriterion("flag between", value1, value2, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagNotBetween(Integer value1, Integer value2) {
			addCriterion("flag not between", value1, value2, "flag");
			return (Criteria) this;
		}

		public Criteria andArrowIsNull() {
			addCriterion("arrow is null");
			return (Criteria) this;
		}

		public Criteria andArrowIsNotNull() {
			addCriterion("arrow is not null");
			return (Criteria) this;
		}

		public Criteria andArrowEqualTo(String value) {
			addCriterion("arrow =", value, "arrow");
			return (Criteria) this;
		}

		public Criteria andArrowNotEqualTo(String value) {
			addCriterion("arrow <>", value, "arrow");
			return (Criteria) this;
		}

		public Criteria andArrowGreaterThan(String value) {
			addCriterion("arrow >", value, "arrow");
			return (Criteria) this;
		}

		public Criteria andArrowGreaterThanOrEqualTo(String value) {
			addCriterion("arrow >=", value, "arrow");
			return (Criteria) this;
		}

		public Criteria andArrowLessThan(String value) {
			addCriterion("arrow <", value, "arrow");
			return (Criteria) this;
		}

		public Criteria andArrowLessThanOrEqualTo(String value) {
			addCriterion("arrow <=", value, "arrow");
			return (Criteria) this;
		}

		public Criteria andArrowLike(String value) {
			addCriterion("arrow like", value, "arrow");
			return (Criteria) this;
		}

		public Criteria andArrowNotLike(String value) {
			addCriterion("arrow not like", value, "arrow");
			return (Criteria) this;
		}

		public Criteria andArrowIn(List<String> values) {
			addCriterion("arrow in", values, "arrow");
			return (Criteria) this;
		}

		public Criteria andArrowNotIn(List<String> values) {
			addCriterion("arrow not in", values, "arrow");
			return (Criteria) this;
		}

		public Criteria andArrowBetween(String value1, String value2) {
			addCriterion("arrow between", value1, value2, "arrow");
			return (Criteria) this;
		}

		public Criteria andArrowNotBetween(String value1, String value2) {
			addCriterion("arrow not between", value1, value2, "arrow");
			return (Criteria) this;
		}

		public Criteria andPrefIsNull() {
			addCriterion("pref is null");
			return (Criteria) this;
		}

		public Criteria andPrefIsNotNull() {
			addCriterion("pref is not null");
			return (Criteria) this;
		}

		public Criteria andPrefEqualTo(String value) {
			addCriterion("pref =", value, "pref");
			return (Criteria) this;
		}

		public Criteria andPrefNotEqualTo(String value) {
			addCriterion("pref <>", value, "pref");
			return (Criteria) this;
		}

		public Criteria andPrefGreaterThan(String value) {
			addCriterion("pref >", value, "pref");
			return (Criteria) this;
		}

		public Criteria andPrefGreaterThanOrEqualTo(String value) {
			addCriterion("pref >=", value, "pref");
			return (Criteria) this;
		}

		public Criteria andPrefLessThan(String value) {
			addCriterion("pref <", value, "pref");
			return (Criteria) this;
		}

		public Criteria andPrefLessThanOrEqualTo(String value) {
			addCriterion("pref <=", value, "pref");
			return (Criteria) this;
		}

		public Criteria andPrefLike(String value) {
			addCriterion("pref like", value, "pref");
			return (Criteria) this;
		}

		public Criteria andPrefNotLike(String value) {
			addCriterion("pref not like", value, "pref");
			return (Criteria) this;
		}

		public Criteria andPrefIn(List<String> values) {
			addCriterion("pref in", values, "pref");
			return (Criteria) this;
		}

		public Criteria andPrefNotIn(List<String> values) {
			addCriterion("pref not in", values, "pref");
			return (Criteria) this;
		}

		public Criteria andPrefBetween(String value1, String value2) {
			addCriterion("pref between", value1, value2, "pref");
			return (Criteria) this;
		}

		public Criteria andPrefNotBetween(String value1, String value2) {
			addCriterion("pref not between", value1, value2, "pref");
			return (Criteria) this;
		}

		public Criteria andPref1IsNull() {
			addCriterion("pref1 is null");
			return (Criteria) this;
		}

		public Criteria andPref1IsNotNull() {
			addCriterion("pref1 is not null");
			return (Criteria) this;
		}

		public Criteria andPref1EqualTo(String value) {
			addCriterion("pref1 =", value, "pref1");
			return (Criteria) this;
		}

		public Criteria andPref1NotEqualTo(String value) {
			addCriterion("pref1 <>", value, "pref1");
			return (Criteria) this;
		}

		public Criteria andPref1GreaterThan(String value) {
			addCriterion("pref1 >", value, "pref1");
			return (Criteria) this;
		}

		public Criteria andPref1GreaterThanOrEqualTo(String value) {
			addCriterion("pref1 >=", value, "pref1");
			return (Criteria) this;
		}

		public Criteria andPref1LessThan(String value) {
			addCriterion("pref1 <", value, "pref1");
			return (Criteria) this;
		}

		public Criteria andPref1LessThanOrEqualTo(String value) {
			addCriterion("pref1 <=", value, "pref1");
			return (Criteria) this;
		}

		public Criteria andPref1Like(String value) {
			addCriterion("pref1 like", value, "pref1");
			return (Criteria) this;
		}

		public Criteria andPref1NotLike(String value) {
			addCriterion("pref1 not like", value, "pref1");
			return (Criteria) this;
		}

		public Criteria andPref1In(List<String> values) {
			addCriterion("pref1 in", values, "pref1");
			return (Criteria) this;
		}

		public Criteria andPref1NotIn(List<String> values) {
			addCriterion("pref1 not in", values, "pref1");
			return (Criteria) this;
		}

		public Criteria andPref1Between(String value1, String value2) {
			addCriterion("pref1 between", value1, value2, "pref1");
			return (Criteria) this;
		}

		public Criteria andPref1NotBetween(String value1, String value2) {
			addCriterion("pref1 not between", value1, value2, "pref1");
			return (Criteria) this;
		}

		public Criteria andStrongIsNull() {
			addCriterion("strong is null");
			return (Criteria) this;
		}

		public Criteria andStrongIsNotNull() {
			addCriterion("strong is not null");
			return (Criteria) this;
		}

		public Criteria andStrongEqualTo(Double value) {
			addCriterion("strong =", value, "strong");
			return (Criteria) this;
		}

		public Criteria andStrongNotEqualTo(Double value) {
			addCriterion("strong <>", value, "strong");
			return (Criteria) this;
		}

		public Criteria andStrongGreaterThan(Double value) {
			addCriterion("strong >", value, "strong");
			return (Criteria) this;
		}

		public Criteria andStrongGreaterThanOrEqualTo(Double value) {
			addCriterion("strong >=", value, "strong");
			return (Criteria) this;
		}

		public Criteria andStrongLessThan(Double value) {
			addCriterion("strong <", value, "strong");
			return (Criteria) this;
		}

		public Criteria andStrongLessThanOrEqualTo(Double value) {
			addCriterion("strong <=", value, "strong");
			return (Criteria) this;
		}

		public Criteria andStrongIn(List<Double> values) {
			addCriterion("strong in", values, "strong");
			return (Criteria) this;
		}

		public Criteria andStrongNotIn(List<Double> values) {
			addCriterion("strong not in", values, "strong");
			return (Criteria) this;
		}

		public Criteria andStrongBetween(Double value1, Double value2) {
			addCriterion("strong between", value1, value2, "strong");
			return (Criteria) this;
		}

		public Criteria andStrongNotBetween(Double value1, Double value2) {
			addCriterion("strong not between", value1, value2, "strong");
			return (Criteria) this;
		}

		public Criteria andDexIsNull() {
			addCriterion("dex is null");
			return (Criteria) this;
		}

		public Criteria andDexIsNotNull() {
			addCriterion("dex is not null");
			return (Criteria) this;
		}

		public Criteria andDexEqualTo(Double value) {
			addCriterion("dex =", value, "dex");
			return (Criteria) this;
		}

		public Criteria andDexNotEqualTo(Double value) {
			addCriterion("dex <>", value, "dex");
			return (Criteria) this;
		}

		public Criteria andDexGreaterThan(Double value) {
			addCriterion("dex >", value, "dex");
			return (Criteria) this;
		}

		public Criteria andDexGreaterThanOrEqualTo(Double value) {
			addCriterion("dex >=", value, "dex");
			return (Criteria) this;
		}

		public Criteria andDexLessThan(Double value) {
			addCriterion("dex <", value, "dex");
			return (Criteria) this;
		}

		public Criteria andDexLessThanOrEqualTo(Double value) {
			addCriterion("dex <=", value, "dex");
			return (Criteria) this;
		}

		public Criteria andDexIn(List<Double> values) {
			addCriterion("dex in", values, "dex");
			return (Criteria) this;
		}

		public Criteria andDexNotIn(List<Double> values) {
			addCriterion("dex not in", values, "dex");
			return (Criteria) this;
		}

		public Criteria andDexBetween(Double value1, Double value2) {
			addCriterion("dex between", value1, value2, "dex");
			return (Criteria) this;
		}

		public Criteria andDexNotBetween(Double value1, Double value2) {
			addCriterion("dex not between", value1, value2, "dex");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.stockaction
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.stockaction
     *
     * @mbg.generated do_not_delete_during_merge Tue Oct 31 17:43:08 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}