package com.stash.model;

import java.util.Date;

public class StockactionModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.stockaction.id
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.stockaction.action
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Integer action;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.stockaction.ftime
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Integer ftime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.stockaction.ltime
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Integer ltime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.stockaction.time
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.stockaction.queue
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private String queue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.stockaction.gw
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private String gw;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.stockaction.type
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.stockaction.content
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.stockaction.detail
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private String detail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.stockaction.flag
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Integer flag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.stockaction.arrow
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private String arrow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.stockaction.pref
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private String pref;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.stockaction.pref1
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private String pref1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.stockaction.strong
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Double strong;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.stockaction.dex
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	private Double dex;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.stockaction.id
	 * @return  the value of public.stockaction.id
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.stockaction.id
	 * @param id  the value for public.stockaction.id
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.stockaction.action
	 * @return  the value of public.stockaction.action
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Integer getAction() {
		return action;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.stockaction.action
	 * @param action  the value for public.stockaction.action
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setAction(Integer action) {
		this.action = action;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.stockaction.ftime
	 * @return  the value of public.stockaction.ftime
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Integer getFtime() {
		return ftime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.stockaction.ftime
	 * @param ftime  the value for public.stockaction.ftime
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setFtime(Integer ftime) {
		this.ftime = ftime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.stockaction.ltime
	 * @return  the value of public.stockaction.ltime
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Integer getLtime() {
		return ltime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.stockaction.ltime
	 * @param ltime  the value for public.stockaction.ltime
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setLtime(Integer ltime) {
		this.ltime = ltime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.stockaction.time
	 * @return  the value of public.stockaction.time
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.stockaction.time
	 * @param time  the value for public.stockaction.time
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.stockaction.queue
	 * @return  the value of public.stockaction.queue
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public String getQueue() {
		return queue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.stockaction.queue
	 * @param queue  the value for public.stockaction.queue
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setQueue(String queue) {
		this.queue = queue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.stockaction.gw
	 * @return  the value of public.stockaction.gw
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public String getGw() {
		return gw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.stockaction.gw
	 * @param gw  the value for public.stockaction.gw
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setGw(String gw) {
		this.gw = gw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.stockaction.type
	 * @return  the value of public.stockaction.type
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.stockaction.type
	 * @param type  the value for public.stockaction.type
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.stockaction.content
	 * @return  the value of public.stockaction.content
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.stockaction.content
	 * @param content  the value for public.stockaction.content
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.stockaction.detail
	 * @return  the value of public.stockaction.detail
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public String getDetail() {
		return detail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.stockaction.detail
	 * @param detail  the value for public.stockaction.detail
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setDetail(String detail) {
		this.detail = detail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.stockaction.flag
	 * @return  the value of public.stockaction.flag
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Integer getFlag() {
		return flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.stockaction.flag
	 * @param flag  the value for public.stockaction.flag
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setFlag(Integer flag) {
		this.flag = flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.stockaction.arrow
	 * @return  the value of public.stockaction.arrow
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public String getArrow() {
		return arrow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.stockaction.arrow
	 * @param arrow  the value for public.stockaction.arrow
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setArrow(String arrow) {
		this.arrow = arrow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.stockaction.pref
	 * @return  the value of public.stockaction.pref
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public String getPref() {
		return pref;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.stockaction.pref
	 * @param pref  the value for public.stockaction.pref
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setPref(String pref) {
		this.pref = pref;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.stockaction.pref1
	 * @return  the value of public.stockaction.pref1
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public String getPref1() {
		return pref1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.stockaction.pref1
	 * @param pref1  the value for public.stockaction.pref1
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setPref1(String pref1) {
		this.pref1 = pref1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.stockaction.strong
	 * @return  the value of public.stockaction.strong
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Double getStrong() {
		return strong;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.stockaction.strong
	 * @param strong  the value for public.stockaction.strong
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setStrong(Double strong) {
		this.strong = strong;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.stockaction.dex
	 * @return  the value of public.stockaction.dex
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Double getDex() {
		return dex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.stockaction.dex
	 * @param dex  the value for public.stockaction.dex
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setDex(Double dex) {
		this.dex = dex;
	}
}