package com.stash.model;

import java.util.Date;

public class Ting20Model {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ting20.id
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ting20.code
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ting20.count
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ting20.date
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ting20.id
     *
     * @return the value of public.ting20.id
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ting20.id
     *
     * @param id the value for public.ting20.id
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ting20.code
     *
     * @return the value of public.ting20.code
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ting20.code
     *
     * @param code the value for public.ting20.code
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ting20.count
     *
     * @return the value of public.ting20.count
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ting20.count
     *
     * @param count the value for public.ting20.count
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ting20.date
     *
     * @return the value of public.ting20.date
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ting20.date
     *
     * @param date the value for public.ting20.date
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setDate(Date date) {
        this.date = date;
    }
}