package com.stash.model;

import java.util.ArrayList;
import java.util.List;

public class VersionModelExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.version
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.version
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.version
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.version
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public VersionModelExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.version
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.version
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.version
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.version
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.version
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.version
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.version
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.version
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.version
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.version
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.version
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andVerIsNull() {
			addCriterion("ver is null");
			return (Criteria) this;
		}

		public Criteria andVerIsNotNull() {
			addCriterion("ver is not null");
			return (Criteria) this;
		}

		public Criteria andVerEqualTo(Integer value) {
			addCriterion("ver =", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerNotEqualTo(Integer value) {
			addCriterion("ver <>", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerGreaterThan(Integer value) {
			addCriterion("ver >", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerGreaterThanOrEqualTo(Integer value) {
			addCriterion("ver >=", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerLessThan(Integer value) {
			addCriterion("ver <", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerLessThanOrEqualTo(Integer value) {
			addCriterion("ver <=", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerIn(List<Integer> values) {
			addCriterion("ver in", values, "ver");
			return (Criteria) this;
		}

		public Criteria andVerNotIn(List<Integer> values) {
			addCriterion("ver not in", values, "ver");
			return (Criteria) this;
		}

		public Criteria andVerBetween(Integer value1, Integer value2) {
			addCriterion("ver between", value1, value2, "ver");
			return (Criteria) this;
		}

		public Criteria andVerNotBetween(Integer value1, Integer value2) {
			addCriterion("ver not between", value1, value2, "ver");
			return (Criteria) this;
		}

		public Criteria andBcheckIsNull() {
			addCriterion("bcheck is null");
			return (Criteria) this;
		}

		public Criteria andBcheckIsNotNull() {
			addCriterion("bcheck is not null");
			return (Criteria) this;
		}

		public Criteria andBcheckEqualTo(Short value) {
			addCriterion("bcheck =", value, "bcheck");
			return (Criteria) this;
		}

		public Criteria andBcheckNotEqualTo(Short value) {
			addCriterion("bcheck <>", value, "bcheck");
			return (Criteria) this;
		}

		public Criteria andBcheckGreaterThan(Short value) {
			addCriterion("bcheck >", value, "bcheck");
			return (Criteria) this;
		}

		public Criteria andBcheckGreaterThanOrEqualTo(Short value) {
			addCriterion("bcheck >=", value, "bcheck");
			return (Criteria) this;
		}

		public Criteria andBcheckLessThan(Short value) {
			addCriterion("bcheck <", value, "bcheck");
			return (Criteria) this;
		}

		public Criteria andBcheckLessThanOrEqualTo(Short value) {
			addCriterion("bcheck <=", value, "bcheck");
			return (Criteria) this;
		}

		public Criteria andBcheckIn(List<Short> values) {
			addCriterion("bcheck in", values, "bcheck");
			return (Criteria) this;
		}

		public Criteria andBcheckNotIn(List<Short> values) {
			addCriterion("bcheck not in", values, "bcheck");
			return (Criteria) this;
		}

		public Criteria andBcheckBetween(Short value1, Short value2) {
			addCriterion("bcheck between", value1, value2, "bcheck");
			return (Criteria) this;
		}

		public Criteria andBcheckNotBetween(Short value1, Short value2) {
			addCriterion("bcheck not between", value1, value2, "bcheck");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andContentIsNull() {
			addCriterion("content is null");
			return (Criteria) this;
		}

		public Criteria andContentIsNotNull() {
			addCriterion("content is not null");
			return (Criteria) this;
		}

		public Criteria andContentEqualTo(String value) {
			addCriterion("content =", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotEqualTo(String value) {
			addCriterion("content <>", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThan(String value) {
			addCriterion("content >", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThanOrEqualTo(String value) {
			addCriterion("content >=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThan(String value) {
			addCriterion("content <", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThanOrEqualTo(String value) {
			addCriterion("content <=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLike(String value) {
			addCriterion("content like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotLike(String value) {
			addCriterion("content not like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentIn(List<String> values) {
			addCriterion("content in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotIn(List<String> values) {
			addCriterion("content not in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentBetween(String value1, String value2) {
			addCriterion("content between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotBetween(String value1, String value2) {
			addCriterion("content not between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andUrlIsNull() {
			addCriterion("url is null");
			return (Criteria) this;
		}

		public Criteria andUrlIsNotNull() {
			addCriterion("url is not null");
			return (Criteria) this;
		}

		public Criteria andUrlEqualTo(String value) {
			addCriterion("url =", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotEqualTo(String value) {
			addCriterion("url <>", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlGreaterThan(String value) {
			addCriterion("url >", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlGreaterThanOrEqualTo(String value) {
			addCriterion("url >=", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLessThan(String value) {
			addCriterion("url <", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLessThanOrEqualTo(String value) {
			addCriterion("url <=", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLike(String value) {
			addCriterion("url like", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotLike(String value) {
			addCriterion("url not like", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlIn(List<String> values) {
			addCriterion("url in", values, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotIn(List<String> values) {
			addCriterion("url not in", values, "url");
			return (Criteria) this;
		}

		public Criteria andUrlBetween(String value1, String value2) {
			addCriterion("url between", value1, value2, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotBetween(String value1, String value2) {
			addCriterion("url not between", value1, value2, "url");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(Integer value) {
			addCriterion("type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(Integer value) {
			addCriterion("type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(Integer value) {
			addCriterion("type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(Integer value) {
			addCriterion("type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(Integer value) {
			addCriterion("type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<Integer> values) {
			addCriterion("type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<Integer> values) {
			addCriterion("type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(Integer value1, Integer value2) {
			addCriterion("type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("type not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andExtraIsNull() {
			addCriterion("extra is null");
			return (Criteria) this;
		}

		public Criteria andExtraIsNotNull() {
			addCriterion("extra is not null");
			return (Criteria) this;
		}

		public Criteria andExtraEqualTo(String value) {
			addCriterion("extra =", value, "extra");
			return (Criteria) this;
		}

		public Criteria andExtraNotEqualTo(String value) {
			addCriterion("extra <>", value, "extra");
			return (Criteria) this;
		}

		public Criteria andExtraGreaterThan(String value) {
			addCriterion("extra >", value, "extra");
			return (Criteria) this;
		}

		public Criteria andExtraGreaterThanOrEqualTo(String value) {
			addCriterion("extra >=", value, "extra");
			return (Criteria) this;
		}

		public Criteria andExtraLessThan(String value) {
			addCriterion("extra <", value, "extra");
			return (Criteria) this;
		}

		public Criteria andExtraLessThanOrEqualTo(String value) {
			addCriterion("extra <=", value, "extra");
			return (Criteria) this;
		}

		public Criteria andExtraLike(String value) {
			addCriterion("extra like", value, "extra");
			return (Criteria) this;
		}

		public Criteria andExtraNotLike(String value) {
			addCriterion("extra not like", value, "extra");
			return (Criteria) this;
		}

		public Criteria andExtraIn(List<String> values) {
			addCriterion("extra in", values, "extra");
			return (Criteria) this;
		}

		public Criteria andExtraNotIn(List<String> values) {
			addCriterion("extra not in", values, "extra");
			return (Criteria) this;
		}

		public Criteria andExtraBetween(String value1, String value2) {
			addCriterion("extra between", value1, value2, "extra");
			return (Criteria) this;
		}

		public Criteria andExtraNotBetween(String value1, String value2) {
			addCriterion("extra not between", value1, value2, "extra");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.version
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.version
     *
     * @mbg.generated do_not_delete_during_merge Tue Oct 31 17:43:08 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}