package com.stash.model;

public class VersionModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.version.id
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.version.ver
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Integer ver;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.version.bcheck
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Short bcheck;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.version.title
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.version.content
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.version.url
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.version.type
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.version.extra
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	private String extra;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.version.id
	 * @return  the value of public.version.id
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.version.id
	 * @param id  the value for public.version.id
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.version.ver
	 * @return  the value of public.version.ver
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Integer getVer() {
		return ver;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.version.ver
	 * @param ver  the value for public.version.ver
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setVer(Integer ver) {
		this.ver = ver;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.version.bcheck
	 * @return  the value of public.version.bcheck
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Short getBcheck() {
		return bcheck;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.version.bcheck
	 * @param bcheck  the value for public.version.bcheck
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setBcheck(Short bcheck) {
		this.bcheck = bcheck;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.version.title
	 * @return  the value of public.version.title
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.version.title
	 * @param title  the value for public.version.title
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.version.content
	 * @return  the value of public.version.content
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.version.content
	 * @param content  the value for public.version.content
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.version.url
	 * @return  the value of public.version.url
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.version.url
	 * @param url  the value for public.version.url
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.version.type
	 * @return  the value of public.version.type
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.version.type
	 * @param type  the value for public.version.type
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.version.extra
	 * @return  the value of public.version.extra
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public String getExtra() {
		return extra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.version.extra
	 * @param extra  the value for public.version.extra
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	public void setExtra(String extra) {
		this.extra = extra;
	}
}