package com.stash.model;

import java.util.Date;

public class WeakModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.weak.code
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.weak.name
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.weak.time
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.weak.trans
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private Double trans;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.weak.signal
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private Integer signal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.weak.ascrate
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private Double ascrate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.weak.descrate
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private Double descrate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.weak.equalrate
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    private Double equalrate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.weak.code
     *
     * @return the value of public.weak.code
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.weak.code
     *
     * @param code the value for public.weak.code
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.weak.name
     *
     * @return the value of public.weak.name
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.weak.name
     *
     * @param name the value for public.weak.name
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.weak.time
     *
     * @return the value of public.weak.time
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.weak.time
     *
     * @param time the value for public.weak.time
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.weak.trans
     *
     * @return the value of public.weak.trans
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public Double getTrans() {
        return trans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.weak.trans
     *
     * @param trans the value for public.weak.trans
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setTrans(Double trans) {
        this.trans = trans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.weak.signal
     *
     * @return the value of public.weak.signal
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public Integer getSignal() {
        return signal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.weak.signal
     *
     * @param signal the value for public.weak.signal
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setSignal(Integer signal) {
        this.signal = signal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.weak.ascrate
     *
     * @return the value of public.weak.ascrate
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public Double getAscrate() {
        return ascrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.weak.ascrate
     *
     * @param ascrate the value for public.weak.ascrate
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setAscrate(Double ascrate) {
        this.ascrate = ascrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.weak.descrate
     *
     * @return the value of public.weak.descrate
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public Double getDescrate() {
        return descrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.weak.descrate
     *
     * @param descrate the value for public.weak.descrate
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setDescrate(Double descrate) {
        this.descrate = descrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.weak.equalrate
     *
     * @return the value of public.weak.equalrate
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public Double getEqualrate() {
        return equalrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.weak.equalrate
     *
     * @param equalrate the value for public.weak.equalrate
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    public void setEqualrate(Double equalrate) {
        this.equalrate = equalrate;
    }
}