package com.stash.mapper;

import com.stash.model.AllStockModel;
import com.stash.model.AllStockModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AllStockModelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.allstock
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	long countByExample(AllStockModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.allstock
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int deleteByExample(AllStockModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.allstock
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int deleteByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.allstock
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int insert(AllStockModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.allstock
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int insertSelective(AllStockModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.allstock
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	List<AllStockModel> selectByExample(AllStockModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.allstock
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	AllStockModel selectByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.allstock
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByExampleSelective(@Param("record") AllStockModel record, @Param("example") AllStockModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.allstock
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByExample(@Param("record") AllStockModel record, @Param("example") AllStockModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.allstock
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByPrimaryKeySelective(AllStockModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.allstock
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByPrimaryKey(AllStockModel record);
}