package com.stash.mapper;

import com.stash.model.CandTransModel;
import com.stash.model.CandTransModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CandTransModelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.cand_trans
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	long countByExample(CandTransModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.cand_trans
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int deleteByExample(CandTransModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.cand_trans
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.cand_trans
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int insert(CandTransModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.cand_trans
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int insertSelective(CandTransModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.cand_trans
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	List<CandTransModel> selectByExample(CandTransModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.cand_trans
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	CandTransModel selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.cand_trans
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByExampleSelective(@Param("record") CandTransModel record,
			@Param("example") CandTransModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.cand_trans
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByExample(@Param("record") CandTransModel record, @Param("example") CandTransModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.cand_trans
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByPrimaryKeySelective(CandTransModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.cand_trans
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByPrimaryKey(CandTransModel record);
}