package com.stash.mapper;

import com.stash.model.CandRateModel;
import com.stash.model.CandRateModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CandRateModelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.cand_rate
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	long countByExample(CandRateModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.cand_rate
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int deleteByExample(CandRateModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.cand_rate
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.cand_rate
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int insert(CandRateModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.cand_rate
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int insertSelective(CandRateModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.cand_rate
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	List<CandRateModel> selectByExample(CandRateModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.cand_rate
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	CandRateModel selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.cand_rate
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByExampleSelective(@Param("record") CandRateModel record, @Param("example") CandRateModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.cand_rate
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByExample(@Param("record") CandRateModel record, @Param("example") CandRateModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.cand_rate
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByPrimaryKeySelective(CandRateModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.cand_rate
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByPrimaryKey(CandRateModel record);
}