package com.stash.mapper;

import com.stash.model.CategoryModel;
import com.stash.model.CategoryModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CategoryModelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.category
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	long countByExample(CategoryModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.category
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int deleteByExample(CategoryModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.category
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int deleteByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.category
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int insert(CategoryModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.category
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int insertSelective(CategoryModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.category
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	List<CategoryModel> selectByExample(CategoryModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.category
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	CategoryModel selectByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.category
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByExampleSelective(@Param("record") CategoryModel record, @Param("example") CategoryModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.category
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByExample(@Param("record") CategoryModel record, @Param("example") CategoryModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.category
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByPrimaryKeySelective(CategoryModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.category
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByPrimaryKey(CategoryModel record);
}