package com.stash.mapper;

import com.stash.model.CollectModel;
import com.stash.model.CollectModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CollectModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.collect
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    long countByExample(CollectModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.collect
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int deleteByExample(CollectModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.collect
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.collect
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int insert(CollectModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.collect
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int insertSelective(CollectModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.collect
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    List<CollectModel> selectByExample(CollectModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.collect
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    CollectModel selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.collect
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") CollectModel record, @Param("example") CollectModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.collect
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int updateByExample(@Param("record") CollectModel record, @Param("example") CollectModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.collect
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int updateByPrimaryKeySelective(CollectModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.collect
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int updateByPrimaryKey(CollectModel record);
}