package com.stash.mapper;

import com.stash.model.CTransModel;
import com.stash.model.CTransModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CTransModelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.c_trans
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	long countByExample(CTransModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.c_trans
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int deleteByExample(CTransModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.c_trans
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.c_trans
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int insert(CTransModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.c_trans
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int insertSelective(CTransModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.c_trans
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	List<CTransModel> selectByExample(CTransModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.c_trans
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	CTransModel selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.c_trans
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByExampleSelective(@Param("record") CTransModel record, @Param("example") CTransModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.c_trans
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByExample(@Param("record") CTransModel record, @Param("example") CTransModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.c_trans
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByPrimaryKeySelective(CTransModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.c_trans
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByPrimaryKey(CTransModel record);
}