package com.stash.mapper;

import com.stash.model.DailyModel;
import com.stash.model.DailyModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DailyModelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.daily
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	long countByExample(DailyModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.daily
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int deleteByExample(DailyModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.daily
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.daily
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int insert(DailyModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.daily
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int insertSelective(DailyModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.daily
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	List<DailyModel> selectByExample(DailyModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.daily
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	DailyModel selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.daily
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int updateByExampleSelective(@Param("record") DailyModel record, @Param("example") DailyModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.daily
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int updateByExample(@Param("record") DailyModel record, @Param("example") DailyModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.daily
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int updateByPrimaryKeySelective(DailyModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.daily
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int updateByPrimaryKey(DailyModel record);
}