package com.stash.mapper;

import com.stash.model.HistoryModel;
import com.stash.model.HistoryModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HistoryModelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.history
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	long countByExample(HistoryModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.history
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int deleteByExample(HistoryModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.history
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.history
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int insert(HistoryModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.history
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int insertSelective(HistoryModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.history
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	List<HistoryModel> selectByExample(HistoryModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.history
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	HistoryModel selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.history
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int updateByExampleSelective(@Param("record") HistoryModel record, @Param("example") HistoryModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.history
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int updateByExample(@Param("record") HistoryModel record, @Param("example") HistoryModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.history
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int updateByPrimaryKeySelective(HistoryModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.history
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int updateByPrimaryKey(HistoryModel record);
}