package com.stash.mapper;

import com.stash.model.IndexrecordModel;
import com.stash.model.IndexrecordModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndexrecordModelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.indexrecord
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	long countByExample(IndexrecordModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.indexrecord
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int deleteByExample(IndexrecordModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.indexrecord
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.indexrecord
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int insert(IndexrecordModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.indexrecord
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int insertSelective(IndexrecordModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.indexrecord
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	List<IndexrecordModel> selectByExample(IndexrecordModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.indexrecord
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	IndexrecordModel selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.indexrecord
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int updateByExampleSelective(@Param("record") IndexrecordModel record,
			@Param("example") IndexrecordModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.indexrecord
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int updateByExample(@Param("record") IndexrecordModel record, @Param("example") IndexrecordModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.indexrecord
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int updateByPrimaryKeySelective(IndexrecordModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.indexrecord
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int updateByPrimaryKey(IndexrecordModel record);
}