package com.stash.mapper;

import com.stash.model.MessageModel;
import com.stash.model.MessageModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessageModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.message
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    long countByExample(MessageModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.message
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int deleteByExample(MessageModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.message
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.message
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int insert(MessageModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.message
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int insertSelective(MessageModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.message
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    List<MessageModel> selectByExample(MessageModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.message
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    MessageModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.message
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") MessageModel record, @Param("example") MessageModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.message
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int updateByExample(@Param("record") MessageModel record, @Param("example") MessageModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.message
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int updateByPrimaryKeySelective(MessageModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.message
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int updateByPrimaryKey(MessageModel record);
}