package com.stash.mapper;

import com.stash.model.MincolumnModel;
import com.stash.model.MincolumnModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MincolumnModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.mincolumn
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    long countByExample(MincolumnModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.mincolumn
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int deleteByExample(MincolumnModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.mincolumn
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int insert(MincolumnModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.mincolumn
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int insertSelective(MincolumnModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.mincolumn
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    List<MincolumnModel> selectByExample(MincolumnModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.mincolumn
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") MincolumnModel record, @Param("example") MincolumnModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.mincolumn
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int updateByExample(@Param("record") MincolumnModel record, @Param("example") MincolumnModelExample example);
}