package com.stash.mapper;

import com.stash.model.SignModel;
import com.stash.model.SignModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SignModelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.sign
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	long countByExample(SignModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.sign
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int deleteByExample(SignModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.sign
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int deleteByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.sign
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int insert(SignModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.sign
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int insertSelective(SignModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.sign
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	List<SignModel> selectByExample(SignModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.sign
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	SignModel selectByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.sign
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int updateByExampleSelective(@Param("record") SignModel record, @Param("example") SignModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.sign
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int updateByExample(@Param("record") SignModel record, @Param("example") SignModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.sign
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int updateByPrimaryKeySelective(SignModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.sign
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int updateByPrimaryKey(SignModel record);
}