package com.stash.mapper;

import com.stash.model.StockrecordModel;
import com.stash.model.StockrecordModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockrecordModelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockrecord
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	long countByExample(StockrecordModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockrecord
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int deleteByExample(StockrecordModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockrecord
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockrecord
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int insert(StockrecordModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockrecord
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int insertSelective(StockrecordModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockrecord
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	List<StockrecordModel> selectByExample(StockrecordModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockrecord
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	StockrecordModel selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockrecord
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByExampleSelective(@Param("record") StockrecordModel record,
			@Param("example") StockrecordModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockrecord
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByExample(@Param("record") StockrecordModel record, @Param("example") StockrecordModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockrecord
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByPrimaryKeySelective(StockrecordModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockrecord
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByPrimaryKey(StockrecordModel record);
}