package com.stash.mapper;

import com.stash.model.StockactionModel;
import com.stash.model.StockactionModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockactionModelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockaction
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	long countByExample(StockactionModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockaction
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int deleteByExample(StockactionModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockaction
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockaction
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int insert(StockactionModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockaction
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int insertSelective(StockactionModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockaction
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	List<StockactionModel> selectByExample(StockactionModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockaction
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	StockactionModel selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockaction
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByExampleSelective(@Param("record") StockactionModel record,
			@Param("example") StockactionModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockaction
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByExample(@Param("record") StockactionModel record, @Param("example") StockactionModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockaction
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByPrimaryKeySelective(StockactionModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockaction
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByPrimaryKey(StockactionModel record);
}