package com.stash.mapper;

import com.stash.model.StockdailyModel;
import com.stash.model.StockdailyModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockdailyModelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockdaily
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	long countByExample(StockdailyModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockdaily
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int deleteByExample(StockdailyModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockdaily
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockdaily
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int insert(StockdailyModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockdaily
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int insertSelective(StockdailyModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockdaily
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	List<StockdailyModel> selectByExample(StockdailyModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockdaily
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	StockdailyModel selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockdaily
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByExampleSelective(@Param("record") StockdailyModel record,
			@Param("example") StockdailyModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockdaily
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByExample(@Param("record") StockdailyModel record, @Param("example") StockdailyModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockdaily
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByPrimaryKeySelective(StockdailyModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stockdaily
	 * @mbg.generated  Wed Nov 01 16:41:19 CST 2017
	 */
	int updateByPrimaryKey(StockdailyModel record);
}