package com.stash.mapper;

import com.stash.model.Ting20Model;
import com.stash.model.Ting20ModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Ting20ModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ting20
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    long countByExample(Ting20ModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ting20
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int deleteByExample(Ting20ModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ting20
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ting20
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int insert(Ting20Model record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ting20
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int insertSelective(Ting20Model record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ting20
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    List<Ting20Model> selectByExample(Ting20ModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ting20
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    Ting20Model selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ting20
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") Ting20Model record, @Param("example") Ting20ModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ting20
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int updateByExample(@Param("record") Ting20Model record, @Param("example") Ting20ModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ting20
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int updateByPrimaryKeySelective(Ting20Model record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ting20
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int updateByPrimaryKey(Ting20Model record);
}