package com.stash.mapper;

import com.stash.model.VersionModel;
import com.stash.model.VersionModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VersionModelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.version
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	long countByExample(VersionModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.version
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int deleteByExample(VersionModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.version
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.version
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int insert(VersionModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.version
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int insertSelective(VersionModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.version
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	List<VersionModel> selectByExample(VersionModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.version
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	VersionModel selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.version
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int updateByExampleSelective(@Param("record") VersionModel record, @Param("example") VersionModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.version
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int updateByExample(@Param("record") VersionModel record, @Param("example") VersionModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.version
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int updateByPrimaryKeySelective(VersionModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.version
	 * @mbg.generated  Tue Oct 31 17:57:38 CST 2017
	 */
	int updateByPrimaryKey(VersionModel record);
}