package com.stash.mapper;

import com.stash.model.WeakModel;
import com.stash.model.WeakModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeakModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.weak
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    long countByExample(WeakModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.weak
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int deleteByExample(WeakModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.weak
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int insert(WeakModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.weak
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int insertSelective(WeakModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.weak
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    List<WeakModel> selectByExample(WeakModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.weak
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") WeakModel record, @Param("example") WeakModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.weak
     *
     * @mbg.generated Tue Oct 31 17:57:38 CST 2017
     */
    int updateByExample(@Param("record") WeakModel record, @Param("example") WeakModelExample example);
}